### ISSUE TITLE
Startup fails with "Cannot make directory '/var/run/screen': Permission denied"

### ISSUE THREAD

**Issue by djmccormick** [marcuswhybrow/minecraft-server-manager#279]
When my Ubuntu 14.04.1 LTS (GNU/Linux 3.13.0-43-generic x86_64) boots up I'm seeing an error relating to the startup of minecraft-server-manager:

    [ACTIVE] Server "mercury" starting:
    world
    Maintaining world symbolic links... Done.
    Synchronising flagged worlds on disk to RAM... Done.
    Starting server...Cannot make directory '/var/run/screen': Permission denied^M
    Done.

This results in the server never starting. If I run "msm restart" I get this:

    Stopping servers:
    Server "mercury" was NOT running.
    No servers were running.
    Starting servers:
    [ACTIVE] Server "mercury" starting:
    world
    Maintaining world symbolic links... Done.
    Synchronising flagged worlds on disk to RAM... Done.
    Starting server... Done.

Perhaps this is an Ubuntu-specific issue but I'm wondering if anyone else has run into this and whether or not there's a supported workaround.

Links I've found around the internet regarding this:
- [Ubu the Tech Guru: Ubuntu - Starting Minecraft Server Automagically FAILs](http://ubuntuaddicted.blogspot.com/2014/11/ubuntu-starting-minecraft-server.html)
- [Ubuntu Bug#574773: Cannot make directory '/var/run/screen': Permission denied (convert init to upstart)](https://bugs.launchpad.net/ubuntu/+source/screen/+bug/574773)

**Comment by Kadah** [comment]
Was also having this issue, @ty2u workaround fixed it for me. Startup performance is not important to me on this particular server.

**Comment by JoinJoin** [comment]
As what user are you attempting to run that screen?

**Comment by djmccormick** [comment]
In my case, whatever the default is during system boot with minecraft-server-manager.

**Comment by Kadah** [comment]
@djmccormick  @ty2u pointed to the cause of this, Ubuntu changed the default shell for boot time scripts to dash. Reconfiguring the system back to using bash should resolve it.
