### ISSUE TITLE
1.8.1 Server Not Really Starting or Generating World

### ISSUE THREAD

**Issue by DylanHG** [marcuswhybrow/minecraft-server-manager#283]
When I start my server up using 'msm <servername> start', it gives me this:

world181
Maintaing world symbolic links... Done.
Synchronising flagged worlds on disk to RAM... Done.
Starting server... Done.

But if I run 'msm <servername> status':
Server "servername" is stopped.

I have tried other people's solutions and lowered the amount of RAM to 512MB from 1024MB (the machine has 4GB so this shouldn't have been a problem), but nothing is working.

**Comment by endofcake** [comment]
Hey @DylanHG , did you accept EULA? I think you need to edit eula.txt for the server to start up.

**Comment by DylanHG** [comment]
Ah okay, I don't remember any mention of that in the installation guide - and I don't remember doing that for setting up my 1.7.2 server which worked fine for over a year - but I suppose if it is necessary, I must have done. What about it do I need to change, and what do I change it to?

**Comment by endofcake** [comment]
Maybe it has changed since 1.7.2 version, I don't know.
Just edit /opt/msm/servers/[whatever your server name is]/eula.txt and set it to true:

#By changing the setting below to TRUE you are indicating your agreement to our EULA (https://account.mojang.com/documents/minecraft_eula).

eula=true

**Comment by DylanHG** [comment]
Yes! This worked, thank you so much :)
