### ISSUE TITLE
Can't login to minecraft server?

### ISSUE THREAD

**Issue by DavGerm4** [marcuswhybrow/minecraft-server-manager#288]
I setup everything, and when I try to join the server locally, or off network it just says Connection Refused? I've tried putting in "localhost" or "127.0.0.1" to the server-ip= but still no luck? I've tried changing the port of the server, and still nothing?

Any help here?

**Comment by jrbooth3** [comment]
Are you running Minecraft client from the same machine as the Minecraft server?

**Comment by DavGerm4** [comment]
No. I'm running minecraft on my laptop or desktop. My Ubuntu Server is running the Minecraft Server.

**Comment by jrbooth3** [comment]
Your Minecraft server running on Ubuntu needs to be listening on *.*.*.*

**Comment by DavGerm4** [comment]
Listening on what?

**Comment by jrbooth3** [comment]
Sorry on the Ubuntu server type with Minecraft running
sudo netstat -nl | grep 25565
It should return an address port
Like 192.168.2.1:25565

**Comment by DavGerm4** [comment]
Oh, so I know what IP and port they are. the IP is a Static, and outside the network it has a domain, but even on that I don't get anything... Just says "Can't connect to server" and when I try to join that game, it says "Connection Refused"?

**Comment by DavGerm4** [comment]
also that "sudo netstat -nl | grep 25565" didn't return anything...

**Comment by DavGerm4** [comment]
Ok, now I'm getting a Internal Exception: java.io.IOException: Connection reset by peer.

**Comment by jrbooth3** [comment]
After you started the world you need to change the EULA file to true then restart the world.

**Comment by DavGerm4** [comment]
I feel like we're making some progress... Don't know why I"m having these problems..  Anyway it says now "Internal Exception: java.io.IOException: An existing connection was forcibly closed by the remote host".

There was no EULA.txt file, so I just created one in the main dir where the server.properties file is, and put in the EULA.txt "EULA=TRUE".

**Comment by jrbooth3** [comment]
It would be in servers / world name.  eula.txt eula=true mine is all lower case.

**Comment by kjkazinski** [comment]
Are you have port forwarding at the router?

When you are trying to connect are you in the same subnet as the server?

**Comment by DavGerm4** [comment]
from what I can gather, it just seems like the main command to start a vanilla minecraft server, the  java -Xmx4096M -Xms4096M -jar spigot-1.8.jar nogui command, doesn't seem like it is ever running... Like if I run that command for the exact port, it will work. I was just installing msm to make things a little easier...

**Comment by kjkazinski** [comment]
Try starting minecraft with the gui, remove the -nogui by typing the command on a command line.  Then try and log in.

This will help verify everything is working without MSM

**Comment by DavGerm4** [comment]
Ok I finally figured it out i think. I changed the default "server.jar" to "spigot-1.8.6.jar" and when i ran the msm start command it was taking a little longer to setup everything. Then it said it was done setting up, so I clicked the server, and it worked!

Thanks you guys for sticking with me to help! I'll keep testing this, hope all goes well!

**Comment by kjkazinski** [comment]
You should create a link called server.jar to the jar file you wish to run.

**Comment by endofcake** [comment]
Looks like this has been resolved. Closing now.
